# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EncoderTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 190)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 471, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 161, 91))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_Ticks = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Ticks.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_Ticks.setObjectName("radioButton_Ticks")
        self.radioButton_Distance = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Distance.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.radioButton_Distance.setObjectName("radioButton_Distance")
        self.pushButton_send = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_send.setGeometry(QtCore.QRect(380, 30, 75, 101))
        self.pushButton_send.setObjectName("pushButton_send")
        self.comboBox_movement = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_movement.setGeometry(QtCore.QRect(180, 100, 69, 22))
        self.comboBox_movement.setObjectName("comboBox_movement")
        self.comboBox_movement.addItem("")
        self.comboBox_movement.addItem("")
        self.comboBox_movement.addItem("")
        self.comboBox_movement.addItem("")
        self.lineEdit_direction = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_direction.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.lineEdit_direction.setObjectName("lineEdit_direction")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(300, 40, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit_distance = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_distance.setGeometry(QtCore.QRect(180, 70, 113, 20))
        self.lineEdit_distance.setObjectName("lineEdit_distance")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Tests"))
        self.groupBox.setTitle(_translate("MainWindow", "Move Type"))
        self.radioButton_Ticks.setText(_translate("MainWindow", "Ticks"))
        self.radioButton_Distance.setText(_translate("MainWindow", "Distance in mm"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.comboBox_movement.setItemText(0, _translate("MainWindow", "FWD"))
        self.comboBox_movement.setItemText(1, _translate("MainWindow", "BACK"))
        self.comboBox_movement.setItemText(2, _translate("MainWindow", "LEFT"))
        self.comboBox_movement.setItemText(3, _translate("MainWindow", "RIGHT"))
        self.label.setText(_translate("MainWindow", "From North"))
        self.label_2.setText(_translate("MainWindow", "Distance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
