#include "Arduino.h"
#include "ABTraceCBK.h"

 /* Formated JSON string to send to Server software */
#define JSON_TRACE_STR_VALUE_V1 "{\"M\":%d,\"T\":%d,\"N\":%d,\"A\":%d,\"B\":%d,\"C\":%d,\"D\":%d}@"


extern void dispatchTraceValue(uint8_t msgType, uint16_t traceId, int args, int value1, int value2, int value3, int value4);

extern void ABTraceUserCallHandler();

/* ABTrace callback */
ABTraceCallback_t ABTraceCallbackList[10]; /* this number shall come from autogenerated code */

void dispatchTraceValue(uint8_t msgType, uint16_t traceId, int args, int value1, int value2, int value3, int value4)
{
    char temp[100];
    /*****************************--------- FID----TID---------*/
    sprintf(temp,JSON_TRACE_STR_VALUE_V1,
                                                       /*FID*/(uint8_t)msgType,    /*1*/
                                                       /*TID*/(uint16_t)traceId,    /*2*/
                                            /*uint8_t*/ /*DT*/(int)args,               /*3*/
                                            /*int*/     /*D1*/(int)value1,           /*4*/
                                            /*int*/     /*D2*/(int)value2,               /*5*/
                                            /*int*/     /*D3*/(int)value3,               /*6*/
                                            /*int*/     /*D4*/(int)value4);              /*7*/

    Serial.print(temp);
}

void ABTraceUserCallHandler()
{
    char temp[100];
    char delim[2] = "$";
    char *param_str;
    uint8_t *param;
    uint8_t callabckIndex;
    uint8_t len;
    memset(temp,0x00,100);
    Serial.readBytesUntil('#',temp,100);
    param_str = strtok(temp,delim);
    callabckIndex = atoi(param_str);
    param = (uint8_t*)strtok(NULL,delim);
    param_str = strtok(NULL,delim);
    len = atoi(param_str);
    ABTraceCallbackList[callabckIndex].callback(len,param);
}